$( document ).ready(function() {
  $('.mail').click(function(){
    $('.email').slideToggle();
  });
  $('.toggle-CLC').click(function(){
    $('.desc-CLC').slideToggle();
    $('.title-CLC').toggleClass('title-right-selected');
    $('.circle-CLC').toggleClass('circle-right-selected');
  });
  $('.toggle-JSH').click(function(){
    $('.desc-JSH').slideToggle();
    $('.title-JSH').toggleClass('title-left-selected');
    $('.circle-JSH').toggleClass('circle-left-selected');
  });
  $('.toggle-Migo').click(function(){
    $('.desc-Migo').slideToggle();
    $('.title-Migo').toggleClass('title-right-selected');
    $('.circle-Migo').toggleClass('circle-right-selected');
  });
  $('.toggle-FB').click(function(){
    $('.desc-FB').slideToggle();
    $('.title-FB').toggleClass('title-left-selected');
    $('.circle-FB').toggleClass('circle-left-selected');
  });
  $('.toggle-Ada').click(function(){
    $('.desc-Ada').slideToggle();
    $('.title-Ada').toggleClass('title-right-selected');
    $('.circle-Ada').toggleClass('circle-right-selected');
  });
  $('.toggle-HHS').click(function(){
    $('.desc-HHS').slideToggle();
    $('.title-HHS').toggleClass('title-right-selected');
    $('.circle-HHS').toggleClass('circle-right-selected');
  });
});
